FROM maven:3.8.4-openjdk-11-slim AS build

WORKDIR /app
RUN mkdir -p /app/src/main/java/com/example && \
    mkdir -p /app/src/main/resources && \
    mkdir -p /app/src/test/java

COPY conf/pom.xml /app/pom.xml
COPY jobs/WordCount.java /app/src/main/java/com/example/WordCount.java

RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

# Copy the JAR file generated by Maven from the build stage to the runtime stage
COPY --from=build /app/target/WordCount-1.0-SNAPSHOT.jar /app/WordCount.jar

# Mount a volume to store the artifact on the host system
VOLUME /app/output

# Copy the generated jar to the mounted volume
RUN cp /app/WordCount.jar /app/output/WordCount.jar

CMD ["tail", "-f", "/dev/null"]
